nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: 'https://yarn.build/latest'

yarnPath: .yarn/releases/yarn-berry.cjs

logFilters:
  - code: 'YN0062'
    level: 'discard'
